### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by yormi** [brian-watkins/elmer#1]
Hi mate !

Elmer looks great... the only problem I have so far is during installation:

> $ elm-test
Error: Your .elm/packages/ directory may be corrupted. I was led to believe that
brian-watkins/elmer existed, but I could not find anything when I went to look
up the published versions of this package.

I followed the instructions here: http://elmer-test.cfapps.io/

I'm just wondering what is that .elm/packages/ directory it's talking about.

**Comment by brian-watkins** [comment]
Can you check to see what version of elm-test you have installed? I get this problem with the very latest release of the elm-test node-test-runner (0.18.8). But if I downgrade to 0.18.7 then things work fine. Try `npm install -g elm-test@0.18.7` and let me know how it goes.

**Comment by yormi** [comment]
I've just tried but no success :(

I even wiped the whole global `node-modules` but no luck with `elm-test@0.18.7`

Another idea ?

**Comment by brian-watkins** [comment]
Did you install elm-github-install? `npm install elm-github-install -g`

Here are the steps I've followed to create a project from scratch (assuming you've install elm-test@0.18.7). Can you try this and let me know what happens?

1. `mkdir my-new-project`
2. `cd my-new-project`
3. `elm-test init`
4. `cd tests`
5. Edit package.json and add to the dependencies `"brian-watkins/elmer": "3.0.0 <= v < 4.0.0"`
6. `elm-install`
7. `cd ..`
8. `elm-test`

Hopefully, you should see elm-test compile the code and show one pending test. Otherwise, could you see if there are files in the directory `tests/elm-stuff/packages/brian-watkins/elmer/3.0.0/`? I've only tried this on a mac, so if you're on a different platform, let me know that too.

**Comment by yormi** [comment]
Oh perfect ! Thanks mate !

The instruction from scratch worked.
I was wondering why it was not with my project... 
Deleted the `elm-stuff` directory from the project root and `tests/` directory.
Tried again and it worked.

I'm not sure I get what happenned...I guess I just needed to delete it to force rebuilding through `elm-test@0.18.7`.

Thanks again for your work :)
