### ISSUE TITLE
Elmer Tests "Encountered a native task." on a Stubbed Parameter-less Function

### ISSUE THREAD

**Issue by crippere-shieldsrx** [brian-watkins/elmer#4]
Elmer tests fail, stating that they have found an unstubbed action, even when a stub exists for the task in a parameter-less calling function. 

```
    Encountered a native task.
    Stub any task-generating functions with Task.succeed or Task.fail as necessary.
```

The quick solution is to not use a parameter-less function, such as by adding an unused parameter to the function.  The function:

```
getMyJson : Cmd Msg
getMyJson =
    let
        url =
            "/api/anything"
    in
    Http.send MyGetResponse <| Http.get url decodeMyJson

...

stubGetMyJsonResponse : HttpResponseStub
stubGetMyJsonResponse =
    Stub.for apiRoutes.getMyJson
        |> withBody getMyJsonResponse

```

...can be worked-around by causing the function to take an unused parameter:

```
getMyJson : () -> Cmd Msg
getMyJson _ =
    let
        url =
            "/api/anything"
    in
    Http.send MyGetResponse <| Http.get url decodeMyJson
```

But, rather than working-around this issue, could the tooling be made to support stubbing parameter-less functions?

Dr. Watkins, we have discussed this issue before, in Cambridge.  The thought was that either Elm or Elmer optimizes away an obviously-deterministic parameter-less function, leaving nothing that the stub can stub for.  This issue bit us again recently (but got resolved!), and for that, we wanted to (if nothing else) create some notes on the internet for the greater Elm and Elmer community.

**Comment by brian-watkins** [comment]
You're right that it's not possible to stub a function called as part of the definition of a value (a parameter-less function), since Elm seems to compute values (ie, execute parameter-less functions) at compile time and Elmer can only override functions at run time. 

I guess I'd encourage you to consider how you're structuring your code. It's common that test-driven development pushes one to structure code in a way that makes it easy to test. It turns out that, when we do this, besides making the code easier to test, we get software that's usually divided up into smaller chunks that are easier to reason about. So, a good thing all around. 

I think by creating a value that's just a `Cmd Msg`, you're trying to separate your code a bit. You've probably got an `update` function that returns something like `(model, getMyJson)`, which is easier to read than `(model, Http.send <| Http.get etc...)`. That seems like a good instinct to me, but if you shift the boundary a bit, things may get easier to test and reason about. Why is `MyGetResponse` a part of `getMyJson`? One could argue that `MyGetResponse` is more naturally a concern of the `update` function. So you could restructure `getMyJson` like so:

```
getMyJson : (Result Http.Error String -> Msg) -> Cmd Msg
getMyJson tagger =
  let
        url =
            "/api/anything"
    in
    Http.send tagger <| Http.get url decodeMyJson
```

Now you've got a *function* that takes a tagger as an argument. Stubbing Http responses with Elmer will work just fine, *and*, more importantly, you've made your code a bit easier to reason about. When I look at `getMyJson` I don't have to remember what `MyGetResponse` is; the type tells me that. And if I need to change the tagger later, I don't have to change this code. In addition, because my update function will now return something like: `(model, getMyJson MyGetResponse)`, it's arguably clearer from looking at the update function how the various cases handled by that function are related. 

So, yep, there's a limitation that Elmer can't really overcome. But if you structure your code carefully, you can work around this, and just maybe end up with code that's easier to reason about. Hope this helps!

**Comment by brian-watkins** [comment]
Closing this issue since Elmer is no longer under development. Use [elm-spec](https://package.elm-lang.org/packages/brian-watkins/elm-spec/latest/) instead!
